language: ruby

rvm:
  - 2.2

install:
  - gem install awesome_bot
  - npm install awesome-lint

script:
  - awesome-lint
  - awesome_bot readme.md --allow-dupe --white-list irc.lc,img.shields.io

notifications:
  email: false
